defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

preprocessing:
  active: True
  diastolic_df: "C:/WorkingData/Documents/2_Coding/Python/AAOCA_animation/test_csv_files/diastolic_contours.csv"
  systolic_df: "C:/WorkingData/Documents/2_Coding/Python/AAOCA_animation/test_csv_files/systolic_contours.csv"
  diastolic_output_path: "C:/WorkingData/Documents/2_Coding/Python/AAOCA_animation"
  systolic_output_path: "C:/WorkingData/Documents/2_Coding/Python/AAOCA_animation"
  diastolic_output_dir: 'plots_dia'
  systolic_output_dir: 'plots_sys'
  plot: True
  n_points: 20
  
translation:
  