defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

preprocessing:
  active: True
  plotting: True
  diastolic_df: 'home/yungselm/Documents/AAOCA_animation/test_csv_files/diastolic_contours.csv'
  systolic_df: 'home/yungselm/Documents/AAOCA_animation/test_csv_files/systolic_contours.csv'
  output_dir: 'home/yungselm/Documents/AAOCA_animation'
  n_points: 20
  
translation:
  